// Static symbol -> real company name lookup, resolved once from Screener.in for every
// symbol referenced in CUSTOM_SECTORS (see customSectors.ts) — NOT guessed or hand-typed.
// Sector Rotation cards show the name as the primary label (a stock's ticker is secondary,
// see ConstituentCard.svelte) without any per-card runtime fetch, matching the caching/
// API-usage contract in instructions/caching-performance-instructions.md.
//
// Regenerate by re-running the resolution script for any newly-added symbols and merging the
// result in here — never hand-guess a company name.
// Symbols renamed by corporate actions, so the baskets now use the current NSE ticker
// (confirmed against Angel One's instrument list, which has no listing under the old one):
// AGREVOIND -> BAYERCROP (Bayer Cropscience), SPEL -> SPELS, AMIORG -> ACUTAAS (Ami Organics
// became Acutaas Chemicals), TATAMOTORS -> TMPV (the 2025 demerger; same instrument token).
// Still unresolved, no listing found anywhere: GUJGASLTD (Gujarat Gas, merged) and INDLMETER.
// They fall back to the raw symbol and show "unavailable" until someone removes or replaces them.

export const SYMBOL_NAMES: Record<string, string> = {
	'360ONE': '360 ONE WAM Ltd',
	AADHARHFC: 'Aadhar Housing Finance Ltd',
	AARTIDRUGS: 'Aarti Drugs Ltd',
	ACUTAAS: 'Acutaas Chemicals Ltd',
	TMPV: 'Tata Motors Passenger Vehicles Ltd',
	AARTIIND: 'Aarti Industries Ltd',
	AAVAS: 'AAVAS Financiers Ltd',
	ABB: 'ABB India Ltd',
	ABFRL: 'Aditya Birla Fashion & Retail Ltd',
	ABSLAMC: 'Aditya Birla Sun Life AMC Ltd',
	ACC: 'ACC Ltd',
	ACI: 'Archean Chemical Industries Ltd',
	ADANIENSOL: 'Adani Energy Solutions Ltd',
	ADANIENT: 'Adani Enterprises Ltd',
	ADANIGREEN: 'Adani Green Energy Ltd',
	ADANIPORTS: 'Adani Ports & Special Economic Zone Ltd',
	ADANIPOWER: 'Adani Power Ltd',
	AEQUS: 'Aequs Ltd',
	AEROFLEX: 'Aeroflex Industries Ltd',
	AGARWALEYE: 'Dr Agarwals Health Care Ltd',
	BAYERCROP: 'Bayer Cropscience Ltd',
	AHLUCONT: 'Ahluwalia Contracts (India) Ltd',
	AIMTRON: 'Aimtron Electronics Ltd',
	AKSHOPTFBR: 'Aksh Optifibre Ltd',
	ALLCARGO: 'Allcargo Logistics Ltd',
	ALPEXSOLAR: 'Alpex Solar Ltd',
	AMBUJACEM: 'Ambuja Cements Ltd',
	ANANDRATHI: 'Anand Rathi Wealth Ltd',
	ANANTRAJ: 'Anant Raj Ltd',
	ANGELONE: 'Angel One Ltd',
	ANTHEM: 'Anthem Biosciences Ltd',
	APARINDS: 'Apar Industries Ltd',
	APLAPOLLO: 'APL Apollo Tubes Ltd',
	APOLLO: 'Apollo Micro Systems Ltd',
	APOLLOHOSP: 'Apollo Hospitals Enterprise Ltd',
	APTUS: 'Aptus Value Housing Finance India Ltd',
	ARDEE: 'Ardee Industries Ltd',
	'ARE&M': 'Amara Raja Energy & Mobility Ltd',
	ARVIND: 'Arvind Ltd',
	ASHOKA: 'Ashoka Buildcon Ltd',
	ASIANPAINT: 'Asian Paints Ltd',
	ASMTEC: 'ASM Technologies Ltd',
	ASTERDM: 'Aster DM Quality Care Ltd',
	ASTRAL: 'Astral Ltd',
	ASTRAMICRO: 'Astra Microwave Products Ltd',
	ATHERENERG: 'Ather Energy Ltd',
	ATLANTAELE: 'Atlanta Electricals Ltd',
	ATUL: 'Atul Ltd',
	AUBANK: 'AU Small Finance Bank Ltd',
	AVALON: 'Avalon Technologies Ltd',
	AXISBANK: 'Axis Bank Ltd',
	AXISCADES: 'AXISCADES Technologies Ltd',
	AZAD: 'Azad Engineering Ltd',
	BAHETI: 'Baheti Recycling Industries Ltd',
	BAJAJELEC: 'Bajaj Electricals Ltd',
	BAJAJHFL: 'Bajaj Housing Finance Ltd',
	BAJFINANCE: 'Bajaj Finance Ltd',
	BALKRISIND: 'Balkrishna Industries Ltd',
	BANKBARODA: 'Bank of Baroda',
	BBL: 'Bharat Bijlee Ltd',
	BBOX: 'Black Box Ltd',
	BDL: 'Bharat Dynamics Ltd',
	BEL: 'Bharat Electronics Ltd',
	BEML: 'BEML Ltd',
	BERGEPAINT: 'Berger Paints India Ltd',
	BHARATFORG: 'Bharat Forge Ltd',
	BHARTIARTL: 'Bharti Airtel Ltd',
	BHEL: 'Bharat Heavy Electricals Ltd',
	BIOCON: 'Biocon Ltd',
	BIRET: 'Brookfield India Real Estate Trust',
	BIRLACABLE: 'Birla Cable Ltd',
	BLUEDART: 'Blue Dart Express Ltd',
	BLUESTARCO: 'Blue Star Ltd',
	BORORENEW: 'Borosil Renewables Ltd',
	BPCL: 'Bharat Petroleum Corporation Ltd',
	BRITANNIA: 'Britannia Industries Ltd',
	BSE: 'BSE Ltd',
	CAMS: 'Computer Age Management Services Ltd',
	CANBK: 'Canara Bank',
	CANFINHOME: 'Can Fin Homes Ltd',
	CARERATING: 'CARE Ratings Ltd',
	CARTRADE: 'Cartrade Tech Ltd',
	CDSL: 'Central Depository Services (India) Ltd',
	CENTUM: 'Centum Electronics Ltd',
	CENTURYPLY: 'Century Plyboards (India) Ltd',
	CERA: 'Cera Sanitaryware Ltd',
	CESC: 'CESC Ltd',
	CGPOWER: 'CG Power & Industrial Solutions Ltd',
	CHALET: 'Chalet Hotels Ltd',
	CHAMBLFERT: 'Chambal Fertilisers & Chemicals Ltd',
	CHEMPLASTS: 'Chemplast Sanmar Ltd',
	CHOLAFIN: 'Cholamandalam Investment & Finance Company Ltd',
	CIPLA: 'Cipla Ltd',
	CMRGREEN: 'CMR Green Technologies Ltd',
	COALINDIA: 'Coal India Ltd',
	COCHINSHIP: 'Cochin Shipyard Ltd',
	COHANCE: 'Cohance Lifesciences Ltd',
	COLPAL: 'Colgate-Palmolive (India) Ltd',
	CONCOR: 'Container Corporation Of India Ltd',
	CONCORDBIO: 'Concord Biotech Ltd',
	COROMANDEL: 'Coromandel International Ltd',
	CRAFTSMAN: 'Craftsman Automation Ltd',
	CREDITACC: 'CreditAccess Grameen Ltd',
	CRISIL: 'CRISIL Ltd',
	CROMPTON: 'Crompton Greaves Consumer Electricals Ltd',
	CUMMINSIND: 'Cummins India Ltd',
	CYIENT: 'Cyient Ltd',
	CYIENTDLM: 'Cyient DLM Ltd',
	DABUR: 'Dabur India Ltd',
	DALBHARAT: 'Dalmia Bharat Ltd',
	DATAPATTNS: 'Data Patterns (India) Ltd',
	DCMSHRIRAM: 'DCM Shriram Ltd',
	DCXINDIA: 'DCX Systems Ltd',
	DEEPAKFERT: 'Deepak Fertilisers & Petrochemicals Corp Ltd',
	DEEPAKNTR: 'Deepak Nitrite Ltd',
	DELHIVERY: 'Delhivery Ltd',
	DELTACORP: 'Delta Corp Ltd',
	DEVYANI: 'Devyani International Ltd',
	DHANUKA: 'Dhanuka Agritech Ltd',
	DIACABS: 'Diamond Power Infrastructure Ltd',
	DIVISLAB: 'Divis Laboratories Ltd',
	DIXON: 'Dixon Technologies (India) Ltd',
	DLF: 'DLF Ltd',
	DMART: 'Avenue Supermarts Ltd',
	DRREDDY: 'Dr Reddys Laboratories Ltd',
	DYNAMATECH: 'Dynamatic Technologies Ltd',
	E2E: 'E2E Networks Ltd',
	EASEMYTRIP: 'Easy Trip Planners Ltd',
	ECORECO: 'Eco Recycling Ltd',
	EIHOTEL: 'EIH Ltd',
	ELECON: 'Elecon Engineering Company Ltd',
	ELLEN: 'Ellenbarrie Industrial Gases Ltd',
	EMBASSY: 'Embassy Office Parks REIT',
	ENDURANCE: 'Endurance Technologies Ltd',
	ENGINERSIN: 'Engineers India Ltd',
	ENRIN: 'Siemens Energy India Ltd',
	EQUITASBNK: 'Equitas Small Finance Bank Ltd',
	ESCORTS: 'Escorts Kubota Ltd',
	ETERNAL: 'Eternal Ltd',
	EXIDEIND: 'Exide Industries Ltd',
	FINCABLES: 'Finolex Cables Ltd',
	FINPIPE: 'Finolex Industries Ltd',
	FLUOROCHEM: 'Gujarat Fluorochemicals Ltd',
	FORTIS: 'Fortis Healthcare Ltd',
	FUSION: 'Fusion Finance Ltd',
	GAIL: 'GAIL (India) Ltd',
	GESHIP: 'Great Eastern Shipping Company Ltd',
	GHCL: 'GHCL Ltd',
	GICRE: 'General Insurance Corporation of India',
	GLAND: 'Gland Pharma Ltd',
	GLENMARK: 'Glenmark Pharmaceuticals Ltd',
	GMDCLTD: 'Gujarat Mineral Development Corporation Ltd',
	GMRAIRPORT: 'GMR Airports Ltd',
	GNFC: 'Gujarat Narmada Valley Fertilizers & Chemicals Ltd',
	GODIGIT: 'Go Digit General Insurance Ltd',
	GODREJCP: 'Godrej Consumer Products Ltd',
	GODREJPROP: 'Godrej Properties Ltd',
	GOKEX: 'Gokaldas Exports Ltd',
	GOLDIAM: 'Goldiam International Ltd',
	GRANULES: 'Granules India Ltd',
	GRAVITA: 'Gravita India Ltd',
	GREENLAM: 'Greenlam Industries Ltd',
	GREENPANEL: 'Greenpanel Industries Ltd',
	GRINDWELL: 'Grindwell Norton Ltd',
	GRINFRA: 'G R Infraprojects Ltd',
	GRSE: 'Garden Reach Shipbuilders & Engineers Ltd',
	'GVT&D': 'GE Vernova T&D India Ltd',
	HAL: 'Hindustan Aeronautics Ltd',
	HAVELLS: 'Havells India Ltd',
	HBLENGINE: 'HBL Engineering Ltd',
	HCLTECH: 'HCL Technologies Ltd',
	HDFCAMC: 'HDFC Asset Management Company Ltd',
	HDFCBANK: 'HDFC Bank Ltd',
	HDFCLIFE: 'HDFC Life Insurance Company Ltd',
	HEROMOTOCO: 'Hero MotoCorp Ltd',
	HFCL: 'HFCL Ltd',
	HINDALCO: 'Hindalco Industries Ltd',
	HINDCOPPER: 'Hindustan Copper Ltd',
	HINDPETRO: 'Hindustan Petroleum Corporation Ltd',
	HINDUNILVR: 'Hindustan Unilever Ltd',
	HINDZINC: 'Hindustan Zinc Ltd',
	HIRECT: 'Hirect Ltd',
	HOMEFIRST: 'Home First Finance Company India Ltd',
	HONASA: 'Honasa Consumer Ltd',
	HVAX: 'HVAX Technologies Ltd',
	ICICIBANK: 'ICICI Bank Ltd',
	ICICIGI: 'ICICI Lombard General Insurance Company Ltd',
	ICICIPRULI: 'ICICI Prudential Life Insurance Company Ltd',
	ICRA: 'ICRA Ltd',
	IDEA: 'Vodafone Idea Ltd',
	IDEAFORGE: 'Ideaforge Technology Ltd',
	IEX: 'Indian Energy Exchange Ltd',
	IGL: 'Indraprastha Gas Ltd',
	IIFL: 'IIFL Finance Ltd',
	IIFLCAPS: 'IIFL Capital Services Ltd',
	IKS: 'Inventurus Knowledge Solutions Ltd',
	IMFA: 'Indian Metals & Ferro Alloys Ltd',
	INA: 'Insolation Energy Ltd',
	INDHOTEL: 'Indian Hotels Co Ltd',
	INDIAMART: 'Indiamart Intermesh Ltd',
	INDIASHLTR: 'India Shelter Finance Corporation Ltd',
	INDIGO: 'Interglobe Aviation Ltd',
	INDLMETER: 'IMP Powers Ltd',
	INDOTECH: 'Indo Tech Transformers Ltd',
	INDUSINDBK: 'IndusInd Bank Ltd',
	INDUSTOWER: 'Indus Towers Ltd',
	INFY: 'Infosys Ltd',
	INOXWIND: 'Inox Wind Ltd',
	INSECTICID: 'Insecticides India Ltd',
	INTELLECT: 'Intellect Design Arena Ltd',
	IOC: 'Indian Oil Corporation Ltd',
	IONEXCHANG: 'Ion Exchange (India) Ltd',
	IRB: 'IRB Infrastructure Developers Ltd',
	IRCON: 'Ircon International Ltd',
	IRCTC: 'Indian Railway Catering & Tourism Corporation Ltd',
	IRFC: 'Indian Railway Finance Corporation Ltd',
	ITC: 'ITC Ltd',
	ITCHOTELS: 'ITC Hotels Ltd',
	IXIGO: 'Le Travenues Technology Ltd',
	JAINREC: 'Jain Resource Recycling Ltd',
	JBMA: 'JBM Auto Ltd',
	JINDALSTEL: 'Jindal Steel Ltd',
	JIOFIN: 'Jio Financial Services Ltd',
	JKCEMENT: 'J K Cements Ltd',
	JLHL: 'Jupiter Life Line Hospitals Ltd',
	JSL: 'Jindal Stainless Ltd',
	JSWENERGY: 'JSW Energy Ltd',
	JSWSTEEL: 'JSW Steel Ltd',
	JTEKTINDIA: 'JTEKT India Ltd',
	JUBLFOOD: 'Jubilant Foodworks Ltd',
	JUBLINGREA: 'Jubilant Ingrevia Ltd',
	JUBLPHARMA: 'Jubilant Pharmova Ltd',
	JWL: 'Jupiter Wagons Ltd',
	JYOTICNC: 'Jyoti CNC Automation Ltd',
	KAJARIACER: 'Kajaria Ceramics Ltd',
	KALYANKJIL: 'Kalyan Jewellers India Ltd',
	KANSAINER: 'Kansai Nerolac Paints Ltd',
	KAYNES: 'Kaynes Technology India Ltd',
	KEC: 'KEC International Ltd',
	KECL: 'Kirloskar Electric Company Ltd',
	KEI: 'KEI Industries Ltd',
	KFINTECH: 'KFin Technologies Ltd',
	KIMS: 'Krishna Institute of Medical Sciences Ltd',
	KIRLOSENG: 'Kirloskar Oil Engines Ltd',
	KNRCON: 'KNR Constructions Ltd',
	KOTAKBANK: 'Kotak Mahindra Bank Ltd',
	KOVAI: 'Kovai Medical Center & Hospital Ltd',
	KPIL: 'Kalpataru Projects International Ltd',
	KPITTECH: 'KPIT Technologies Ltd',
	KPRMILL: 'K P R Mill Ltd',
	KRN: 'KRN Heat Exchanger and Refrigeration Ltd',
	KRSNAA: 'Krsnaa Diagnostics Ltd',
	KSB: 'KSB Ltd',
	KSCL: 'Kaveri Seed Company Ltd',
	LALPATHLAB: 'Dr Lal Pathlabs Ltd',
	LAURUSLABS: 'Laurus Labs Ltd',
	LEMONTREE: 'Lemon Tree Hotels Ltd',
	LICHSGFIN: 'LIC Housing Finance Ltd',
	LICI: 'Life Insurance Corporation of India',
	LINDEINDIA: 'Linde India Ltd',
	LODHA: 'Lodha Developers Ltd',
	LT: 'Larsen & Toubro Ltd',
	LTF: 'L&T Finance Ltd',
	LTTS: 'L&T Technology Services Ltd',
	LUMAXIND: 'Lumax Industries Ltd',
	'M&M': 'Mahindra & Mahindra Ltd',
	'M&MFIN': 'Mahindra & Mahindra Financial Services Ltd',
	MAHLOG: 'Mahindra Logistics Ltd',
	MANAPPURAM: 'Manappuram Finance Ltd',
	MANYAVAR: 'Vedant Fashions Ltd',
	MAPMYINDIA: 'C.E. Info Systems Ltd',
	MARICO: 'Marico Ltd',
	MARINE: 'Marine Electricals (India) Ltd',
	MARSONS: 'Marsons Ltd',
	MARUTI: 'Maruti Suzuki India Ltd',
	MAXHEALTH: 'Max Healthcare Institute Ltd',
	MAZDOCK: 'Mazagon Dock Shipbuilders Ltd',
	MCX: 'Multi Commodity Exchange of India Ltd',
	MEDANTA: 'Global Health Ltd',
	METROPOLIS: 'Metropolis Healthcare Ltd',
	MFSL: 'Max Financial Services Ltd',
	MGL: 'Mahanagar Gas Ltd',
	MIDHANI: 'Mishra Dhatu Nigam Ltd',
	MINDSPACE: 'Mindspace Business Parks REIT',
	MINDTECK: 'Mindteck (India) Ltd',
	MOBIKWIK: 'One Mobikwik Systems Ltd',
	MOIL: 'MOIL Ltd',
	MOSCHIP: 'Moschip Technologies Ltd',
	MOTHERSON: 'Samvardhana Motherson International Ltd',
	MOTILALOFS: 'Motilal Oswal Financial Services Ltd',
	MSTCLTD: 'MSTC Ltd',
	MTARTECH: 'MTAR Technologies Ltd',
	MUTHOOTFIN: 'Muthoot Finance Ltd',
	NAMOEWASTE: 'Namo eWaste Management Ltd',
	NATIONALUM: 'National Aluminium Company Ltd',
	NAUKRI: 'Info Edge (India) Ltd',
	NAVINFLUOR: 'Navin Fluorine International Ltd',
	NAZARA: 'Nazara Technologies Ltd',
	NESTLEIND: 'Nestle India Ltd',
	NETWEB: 'Netweb Technologies India Ltd',
	NEULANDLAB: 'Neuland Laboratories Ltd',
	NEWGEN: 'Newgen Software Technologies Ltd',
	NFL: 'National Fertilizer Ltd',
	NH: 'Narayana Hrudayalaya Ltd',
	NHPC: 'NHPC Ltd',
	NIACL: 'New India Assurance Company Ltd',
	NIVABUPA: 'Niva Bupa Health Insurance Company Ltd',
	NMDC: 'NMDC Ltd',
	NTPC: 'NTPC Ltd',
	NTPCGREEN: 'NTPC Green Energy Ltd',
	NUVAMA: 'Nuvama Wealth Management Ltd',
	NUVOCO: 'Nuvoco Vistas Corporation Ltd',
	NXST: 'Nexus Select Trust',
	NYKAA: 'FSN E-Commerce Ventures Ltd',
	OBEROIRLTY: 'Oberoi Realty Ltd',
	OIL: 'Oil India Ltd',
	OLAELEC: 'Ola Electric Mobility Ltd',
	ONGC: 'Oil & Natural Gas Corpn Ltd',
	ONMOBILE: 'OnMobile Global Ltd',
	PAGEIND: 'Page Industries Ltd',
	PARAS: 'Paras Defence and Space Technologies Ltd',
	PARKHOTELS: 'Apeejay Surrendra Park Hotels Ltd',
	PAYTM: 'One 97 Communications Ltd',
	PCJEWELLER: 'PC Jeweller Ltd',
	PETRONET: 'Petronet LNG Ltd',
	PHOENIXLTD: 'Phoenix Mills Ltd',
	PIDILITIND: 'Pidilite Industries Ltd',
	PIIND: 'P I Industries Ltd',
	PITTIENG: 'Pitti Engineering Ltd',
	PNB: 'Punjab National Bank',
	PNBHOUSING: 'PNB Housing Finance Ltd',
	PNCINFRA: 'PNC Infratech Ltd',
	POCL: 'Pondy Oxides & Chemicals Ltd',
	POLICYBZR: 'PB Fintech Ltd',
	POLYCAB: 'Polycab India Ltd',
	POLYMED: 'Poly Medicure Ltd',
	POWERGRID: 'Power Grid Corporation of India Ltd',
	POWERINDIA: 'Hitachi Energy India Ltd',
	PPLPHARMA: 'Piramal Pharma Ltd',
	PRECAM: 'Precision Camshafts Ltd',
	PREMIERENE: 'Premier Energies Ltd',
	PRESTIGE: 'Prestige Estates Projects Ltd',
	PRINCEPIPE: 'Prince Pipes & Fittings Ltd',
	PTCIL: 'PTC Industries Ltd',
	QPOWER: 'Quality Power Electrical Equipments Ltd',
	RAILTEL: 'Railtel Corporation of India Ltd',
	RAINBOW: 'Rainbow Childrens Medicare Ltd',
	RAJESHEXPO: 'Rajesh Exports Ltd',
	RALLIS: 'Rallis India Ltd',
	RAMCOCEM: 'The Ramco Cements Ltd',
	RAYMOND: 'Raymond Ltd',
	RBA: 'Restaurant Brands Asia Ltd',
	RCF: 'Rashtriya Chemicals & Fertilizers Ltd',
	REDINGTON: 'Redington Ltd',
	RELIANCE: 'Reliance Industries Ltd',
	RIR: 'RIR Power Electronics Ltd',
	RKFORGE: 'Ramkrishna Forgings Ltd',
	ROSSTECH: 'Rossell Techsys Ltd',
	RPTECH: 'Rashi Peripherals Ltd',
	RTSPOWR: 'RTS Power Corporation Ltd',
	RVNL: 'Rail Vikas Nigam Ltd',
	SAATVIKGL: 'Saatvik Green Energy Ltd',
	SAHASRA: 'Sahasra Electronic Solutions Ltd',
	SAIL: 'Steel Authority of India Ltd',
	SAILIFE: 'Sai Life Sciences Ltd',
	SANSERA: 'Sansera Engineering Ltd',
	SAPPHIRE: 'Sapphire Foods India Ltd',
	SASKEN: 'Sasken Technologies Ltd',
	SBILIFE: 'SBI Life Insurance Company Ltd',
	SBIN: 'State Bank of India',
	SCHNEIDER: 'Schneider Electric Infrastructure Ltd',
	SCI: 'Shipping Corporation of India Ltd',
	SENCO: 'Senco Gold Ltd',
	SHARDACROP: 'Sharda Cropchem Ltd',
	SHILCTECH: 'Shilchar Technologies Ltd',
	SHREECEM: 'Shree Cement Ltd',
	SHRIRAMFIN: 'Shriram Finance Ltd',
	SIEMENS: 'Siemens Ltd',
	SJVN: 'SJVN Ltd',
	SKFINDIA: 'SKF India Ltd',
	SOLARA: 'Solara Active Pharma Sciences Ltd',
	SOLARINDS: 'Solar Industries India Ltd',
	SOLEX: 'Solex Energy Ltd',
	SOMANYCERA: 'Somany Ceramics Ltd',
	SONACOMS: 'Sona BLW Precision Forgings Ltd',
	SONATSOFTW: 'Sonata Software Ltd',
	SPANDANA: 'Spandana Sphoorty Financial Ltd',
	SPELS: 'SPEL Semiconductor Ltd',
	SPICEJET: 'SpiceJet Ltd',
	SRF: 'SRF Ltd',
	STARHEALTH: 'Star Health & Allied Insurance Company Ltd',
	STLTECH: 'Sterlite Technologies Ltd',
	SUNDARMFIN: 'Sundaram Finance Ltd',
	SUNDRMFAST: 'Sundram Fasteners Ltd',
	SUNLITE: 'Sunlite Recycling Industries Ltd',
	SUNPHARMA: 'Sun Pharmaceutical Industries Ltd',
	SUPRAJIT: 'Suprajit Engineering Ltd',
	SUPREMEIND: 'Supreme Industries Ltd',
	SUPREMEPWR: 'Supreme Power Equipment Ltd',
	SURAKSHA: 'Suraksha Diagnostic Ltd',
	SUZLON: 'Suzlon Energy Ltd',
	SWIGGY: 'Swiggy Ltd',
	SYNGENE: 'Syngene International Ltd',
	SYRMA: 'Syrma SGS Technology Ltd',
	TANAA: 'Taneja Aerospace & Aviation Ltd',
	TARIL: 'Transformers & Rectifiers India Ltd',
	TATACHEM: 'Tata Chemicals Ltd',
	TATACOMM: 'Tata Communications Ltd',
	TATACONSUM: 'Tata Consumer Products Ltd',
	TATAELXSI: 'Tata Elxsi Ltd',
	TATAPOWER: 'Tata Power Company Ltd',
	TATASTEEL: 'Tata Steel Ltd',
	TATATECH: 'Tata Technologies Ltd',
	TATVA: 'Tatva Chintan Pharma Chem Ltd',
	TCI: 'Transport Corporation of India Ltd',
	TCS: 'Tata Consultancy Services Ltd',
	TDPOWERSYS: 'TD Power Systems Ltd',
	TECHM: 'Tech Mahindra Ltd',
	TECHNOE: 'Techno Electric & Engineering Company Ltd',
	TEJASNET: 'Tejas Networks Ltd',
	TEXRAIL: 'Texmaco Rail & Engineering Ltd',
	THANGAMAYL: 'Thangamayil Jewellery Ltd',
	THERMAX: 'Thermax Ltd',
	THYROCARE: 'Thyrocare Technologies Ltd',
	TIMKEN: 'Timken India Ltd',
	TITAGARH: 'Titagarh Rail Systems Ltd',
	TITAN: 'Titan Company Ltd',
	TORNTPOWER: 'Torrent Power Ltd',
	TRANSRAILL: 'Transrail Lighting Ltd',
	TRENT: 'Trent Ltd',
	TRIDENT: 'Trident Ltd',
	TRITURBINE: 'Triveni Turbine Ltd',
	TVSMOTOR: 'TVS Motor Company Ltd',
	UJJIVANSFB: 'Ujjivan Small Finance Bank Ltd',
	ULTRACEMCO: 'UltraTech Cement Ltd',
	UNIMECH: 'Unimech Aerospace and Manufacturing Ltd',
	UNIVCABLES: 'Universal Cables Ltd',
	UNOMINDA: 'Uno Minda Ltd',
	UPL: 'UPL Ltd',
	UTIAMC: 'UTI Asset Management Company Ltd',
	VAIBHAVGBL: 'Vaibhav Global Ltd',
	VARROC: 'Varroc Engineering Ltd',
	VBL: 'Varun Beverages Ltd',
	VEDL: 'Vedanta Ltd',
	VIJAYA: 'Vijaya Diagnostic Centre Ltd',
	VIKRAMSOLR: 'Vikram Solar Ltd',
	VINATIORGA: 'Vinati Organics Ltd',
	VINDHYATEL: 'Vindhya Telelinks Ltd',
	VOLTAMP: 'Voltamp Transformers Ltd',
	VOLTAS: 'Voltas Ltd',
	VRLLOG: 'VRL Logistics Ltd',
	VSTTILLERS: 'VST Tillers Tractors Ltd',
	VTL: 'Vardhman Textiles Ltd',
	WAAREEENER: 'Waaree Energies Ltd',
	WAAREERTL: 'Waaree Renewable Technologies Ltd',
	WALCHANNAG: 'Walchandnagar Industries Ltd',
	WEBELSOLAR: 'Websol Energy System Ltd',
	WELSPUNLIV: 'Welspun Living Ltd',
	WESTLIFE: 'Westlife Foodworld Ltd',
	WHIRLPOOL: 'Whirlpool of India Ltd',
	WIPRO: 'Wipro Ltd',
	ZENSARTECH: 'Zensar Technologies Ltd',
	ZENTEC: 'Zen Technologies Ltd',
	ZODIAC: 'Zodiac Energy Ltd',
	ZYDUSLIFE: 'Zydus Lifesciences Ltd'
};

/** Real company name for a ticker, falling back to the ticker itself if unresolved. */
export function companyName(symbol: string): string {
	return SYMBOL_NAMES[symbol.toUpperCase()] ?? symbol;
}
